package main
import("crypto/rand";"encoding/hex";"encoding/json";"errors";"fmt";"log";"net/http";"os";"strconv";"strings";"sync";"time";"sentinel-server/internal/firewall")
type Peer struct{ID string `json:"id"`;Name string `json:"name"`;PublicKey string `json:"public_key"`;AllowedIPv4 string `json:"allowed_ipv4"`;CreatedAt time.Time `json:"created_at"`}
type PortLease struct{Port uint16 `json:"port"`;PeerID string `json:"peer_id"`;ExpiresAt time.Time `json:"expires_at"`}
type Store struct{mu sync.RWMutex;peers map[string]Peer;ports map[uint16]PortLease}
func NewStore()*Store{return &Store{peers:map[string]Peer{},ports:map[uint16]PortLease{}}}
func randomID()string{b:=make([]byte,12);if _,e:=rand.Read(b);e!=nil{return ""};return hex.EncodeToString(b)}
func(s *Store)allocatePort(peer string)(PortLease,error){s.mu.Lock();defer s.mu.Unlock();now:=time.Now().UTC();for n:=20000;n<=40000;n++{p:=uint16(n);if l,ok:=s.ports[p];ok&&l.ExpiresAt.After(now){continue};l:=PortLease{Port:p,PeerID:peer,ExpiresAt:now.Add(30*time.Minute)};s.ports[p]=l;return l,nil};return PortLease{},errors.New("port pool exhausted")}
func(s *Store)removePort(p uint16){s.mu.Lock();delete(s.ports,p);s.mu.Unlock()}
func jsonResponse(w http.ResponseWriter,status int,payload any){w.Header().Set("Content-Type","application/json");w.WriteHeader(status);_=json.NewEncoder(w).Encode(payload)}
func auth(token string,next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){if token==""{jsonResponse(w,500,map[string]string{"error":"SENTINEL_API_TOKEN is not configured"});return};if r.Header.Get("Authorization")!="Bearer "+token{jsonResponse(w,401,map[string]string{"error":"unauthorized"});return};next.ServeHTTP(w,r)})}
func securityHeaders(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){w.Header().Set("X-Content-Type-Options","nosniff");w.Header().Set("Cache-Control","no-store");next.ServeHTTP(w,r)})}
func limitBody(next http.Handler)http.Handler{return http.HandlerFunc(func(w http.ResponseWriter,r *http.Request){r.Body=http.MaxBytesReader(w,r.Body,64<<10);next.ServeHTTP(w,r)})}
func main(){store:=NewStore();nat:=firewall.New();target:=os.Getenv("SENTINEL_P2P_TARGET");mux:=http.NewServeMux();mux.HandleFunc("/healthz",func(w http.ResponseWriter,_ *http.Request){jsonResponse(w,200,map[string]string{"status":"ok","service":"sentinel-server"})});api:=http.NewServeMux();api.HandleFunc("/api/v1/peers",func(w http.ResponseWriter,r *http.Request){switch r.Method{case http.MethodGet:store.mu.RLock();p:=make([]Peer,0,len(store.peers));for _,v:=range store.peers{p=append(p,v)};store.mu.RUnlock();jsonResponse(w,200,p);case http.MethodPost:var req struct{Name,PublicKey,AllowedIPv4 string};if e:=json.NewDecoder(r.Body).Decode(&req);e!=nil{jsonResponse(w,400,map[string]string{"error":"invalid JSON"});return};if strings.TrimSpace(req.Name)==""||strings.TrimSpace(req.PublicKey)==""||strings.TrimSpace(req.AllowedIPv4)==""{jsonResponse(w,400,map[string]string{"error":"name, public_key and allowed_ipv4 are required"});return};id:=randomID();if id==""{jsonResponse(w,500,map[string]string{"error":"secure id generation failed"});return};p:=Peer{ID:id,Name:req.Name,PublicKey:req.PublicKey,AllowedIPv4:req.AllowedIPv4,CreatedAt:time.Now().UTC()};store.mu.Lock();store.peers[p.ID]=p;store.mu.Unlock();jsonResponse(w,201,p);default:w.Header().Set("Allow","GET, POST");w.WriteHeader(405)}})
api.HandleFunc("/api/v1/p2p/port",func(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{w.Header().Set("Allow","POST");w.WriteHeader(405);return};peer:=r.URL.Query().Get("peer_id");if peer==""{jsonResponse(w,400,map[string]string{"error":"peer_id is required"});return};store.mu.RLock();_,ok:=store.peers[peer];store.mu.RUnlock();if !ok{jsonResponse(w,404,map[string]string{"error":"peer not found"});return};if target==""{jsonResponse(w,503,map[string]string{"error":"SENTINEL_P2P_TARGET is not configured"});return};lease,e:=store.allocatePort(peer);if e!=nil{jsonResponse(w,503,map[string]string{"error":e.Error()});return};if e=nat.ApplyPortForward(lease.Port,target,lease.Port);e!=nil{store.removePort(lease.Port);jsonResponse(w,502,map[string]string{"error":"NAT rule could not be installed"});return};jsonResponse(w,201,lease)})
api.HandleFunc("/api/v1/p2p/revoke",func(w http.ResponseWriter,r *http.Request){if r.Method!=http.MethodPost{w.Header().Set("Allow","POST");w.WriteHeader(405);return};n,e:=strconv.Atoi(r.URL.Query().Get("port"));if e!=nil||n<20000||n>40000{jsonResponse(w,400,map[string]string{"error":"port must be 20000-40000"});return};p:=uint16(n);if e=nat.RemovePortForward(p);e!=nil{jsonResponse(w,502,map[string]string{"error":"NAT rule could not be removed"});return};store.removePort(p);jsonResponse(w,200,map[string]any{"revoked":true,"port":n})})
mux.Handle("/",auth(os.Getenv("SENTINEL_API_TOKEN"),securityHeaders(limitBody(api))));addr:=os.Getenv("SENTINEL_LISTEN");if addr==""{addr=":8080"};if os.Getenv("SENTINEL_API_TOKEN")==""{log.Fatal("SENTINEL_API_TOKEN is required")};log.Printf("sentinel-server listening on %s",addr);if cert,key:=os.Getenv("SENTINEL_TLS_CERT"),os.Getenv("SENTINEL_TLS_KEY");cert!=""&&key!=""{log.Fatal(http.ListenAndServeTLS(addr,cert,key,mux))};if os.Getenv("SENTINEL_ALLOW_PLAINTEXT")!="1"{log.Fatal(fmt.Errorf("TLS certificate/key required; set SENTINEL_ALLOW_PLAINTEXT=1 only for trusted development"))};log.Fatal(http.ListenAndServe(addr,mux))}
